name: self-evolve
on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 4 * * *" # daily at 04:17 UTC

permissions:
  contents: write

jobs:
  evolve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-powershell@v2
      - name: Refresh assets manifest
        shell: pwsh
        run: |
          $ErrorActionPreference='Stop'
          $repo="$PWD"
          $img = @(".png",".jpg",".jpeg",".webp",".svg",".gif",".ico")
          $out = Join-Path $repo 'docs/assets'
          New-Item -ItemType Directory -Force -Path $out | Out-Null
          $items = Get-ChildItem -Path $repo -Recurse -File | Where-Object { $img -contains $_.Extension.ToLower() -and $_.FullName -notmatch '\.git\' } |
            Select-Object @{n='path';e={Resolve-Path -Relative $_.FullName}}, @{n='bytes';e={$_.Length}},
                          @{n='modified';e={$_.LastWriteTime.ToString('o')}}, @{n='alt';e={""}}, @{n='placement';e={""}}, @{n='license';e={""}}
          $json = Join-Path $out 'manifest.json'; $md = Join-Path $out 'manifest.md'
          $items | ConvertTo-Json -Depth 5 | Set-Content -Path $json -Encoding UTF8
          ("# Assets Manifest`n`n" + ($items | ForEach-Object { "* `{0}` — **{1} bytes** — _{2}_".Replace("{0}",$_.path).Replace("{1}",$_.bytes).Replace("{2}",$_.modified) } | Out-String)) |
            Set-Content -Path $md -Encoding UTF8
      - name: Update SESSION_STATUS
        shell: pwsh
        run: |
          $stamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss K"
          New-Item -ItemType Directory -Force -Path docs/bpoe | Out-Null
          @"
# Session Status
- Updated: $stamp
- Branch: $(git rev-parse --abbrev-ref HEAD 2>$null)
- Commit: $(git rev-parse --short HEAD 2>$null)
"@ | Set-Content -Path docs/bpoe/SESSION_STATUS.md -Encoding UTF8
      - name: Commit (gated by ENABLE_AUTOCOMMITS)
        shell: bash
        run: |
          set -e
          echo "ENABLE_AUTOCOMMITS=${{ vars.ENABLE_AUTOCOMMITS }}"
          if [ "${{ vars.ENABLE_AUTOCOMMITS }}" = "true" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git diff --cached --quiet || (git commit -m "auto: self-evolve refresh" && git push)
          else
            echo "Auto-commits disabled; set repo variable ENABLE_AUTOCOMMITS=true to enable."
          fi